"""Fix table naming in DebateLog and DebateSummary

Revision ID: 2d9951150b46
Revises: b9d32853e9ac
Create Date: 2025-05-14 22:41:13.245813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d9951150b46'
down_revision = 'b9d32853e9ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('debate_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('alpha_argument', sa.Text(), nullable=False),
    sa.Column('beta_argument', sa.Text(), nullable=False),
    sa.Column('moderator_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['debate_topic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('debate_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['debate_topic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('debate_summaries')
    op.drop_table('debate_logs')
    # ### end Alembic commands ###
