# ==================== File: glg/agents/marketing_guru.py ====================
"""
The Maven agent: proposes taglines and campaign ideas.
"""
# Name: Maven
# Personality: The Maven is creative and persuasive, excelling in branding and outreach with a flair for storytelling.

from glg.agents.base_agent import BaseAgent

class MavenAgent(BaseAgent):
    def __init__(self):
        super().__init__(
            name="Maven",
            personality="The Maven is creative and persuasive, excelling in branding and outreach with a flair for storytelling."
        )

    def execute(self, product_description):
        """
        Execute the Maven agent's primary function: create compelling marketing materials.

        :param product_description: The description of the product or service.
        :return: The marketing materials generated by the agent.
        """
        import os
        import openai
        from glg.utils.prompts import MARKETING_PROMPT

        key = os.getenv("OPENAI_API_KEY")
        if not key:
            return "Error: OpenAI API key not found or client could not be initialized."

        openai.api_key = key
        prompt = MARKETING_PROMPT.format(description=product_description)

        try:
            response = openai.ChatCompletion.create(
                model="gpt-3.5-turbo",
                messages=[{"role": "user", "content": prompt}]
            )
            return response.choices[0].message.content.strip()
        except Exception as e:
            return f"Error during API call to Maven agent: {str(e)}"
